project:
  type: website
  output-dir: docs

website:
  title: "Comprehensive Guide to Bioinformatics in R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - text: "&nbsp;"
      - Intro.qmd
      - File_download.qmd
      - Pivot.qmd
      - Scatter.qmd
      - Volcano.qmd
      - Line.qmd
      - Sparkline.qmd
      - Kernel.qmd
      - Box and Whisker.qmd
      - Violin.qmd
      - Pheatmap.qmd
      - Hydra.qmd
  
format:
  html:
    theme: simplex
    toc: true
    toc-depth: 5
    toc-location: right
    toc-fixed: true
    toc-title: "In this chapter:"  
    numbered-sections: false