---
title: "Table of Contents"
date: last-modified
date-format: "MMM D, YYY"
format: html
---
| Document | Key Focus| Statues |
|----------|---------|-------------|
| [***Chapter 1***](Intro.qmd)<br>&nbsp;   └ [*Running Libraries*](Intro.qmd#running-libraries)<br>&nbsp;  └ [*Creating Objects*](Intro.qmd#creating-objects)<br>&nbsp; └ [*Colors*](Intro.qmd#colors)<br>&nbsp;  └ [*Numbers*](Intro.qmd#numbers)<br>&nbsp; └ [*Shapes*](Intro.qmd#shapes) |  Introducing Core Concepts in R| Under Construction |
| [***Chapter 2***](File_download.qmd)<br>&nbsp; └ [*Functions in R*](File_download.qmd#functions-in-r)<br>&nbsp;&nbsp;&nbsp;&nbsp;  └ [*Installing Packages (Tidy)*](File_download.qmd#installing-packages-tidy)<br>&nbsp; └ [*Reading Data*](File_download.qmd#reading-data)<br>&nbsp;&nbsp;&nbsp;&nbsp; └ [*Reading Data From Files*](File_download.qmd#reading-data-from-files)<br>&nbsp;&nbsp;&nbsp;&nbsp; └ [*Importing GEO Files*](File_download.qmd#importing-geo-files)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Installing `httr2`*](File_download.qmd#install-httr2)<br>&nbsp; └ [*Using GEOquery*](File_download.qmd#using-geoquery)<br>&nbsp;&nbsp;&nbsp;&nbsp; └ [*Fetching Data*](File_download.qmd#fetching-data)<br>&nbsp;&nbsp;&nbsp;&nbsp; └ [*Working with CEL*](File_download.qmd#working-with-cel) | Explaining File Importing to R| Needs Finalizing |
| [***Chapter 3***](Pivot.qmd)<br>&nbsp; └ [*File Download & Packages*](Pivot.qmd#file-download-&-packages)<br>&nbsp; └ [*Creating a Data Frame*](Pivot.qmd#creating-a-data-frame)<br>&nbsp; └ [*Pivoting a Data Set*](Pivot.qmd#pivoting-a-data-set)<br>&nbsp;&nbsp;&nbsp; └ [*Pivot Longer*](Pivot.qmd#pivot-longer)<br>&nbsp;&nbsp;&nbsp; └ [*Pivot Wider*](Pivot.qmd#pivot-wider) | Rotating Data Frames | Complete |
| [***Chapter 4***](Scatter.qmd)<br>&nbsp; └ [*Basic Scatter*](Scatter.qmd#basic-scatter)<br>&nbsp;&nbsp;&nbsp; └ [*Large Scatter*](Scatter.qmd#large-scatter)<br>&nbsp; └ [*Customized Scatter*](Scatter.qmd#customized-scatter)<br>&nbsp;&nbsp;&nbsp; └ [*Colorization*](Scatter.qmd#colorization)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Standard Error Band*](Scatter.qmd#standard-error-band)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Labeling Outliers*](Scatter.qmd#labeling-outliers)<br>&nbsp;&nbsp;&nbsp; └ [*Error Bars*](Scatter.qmd#error-bars)<br>&nbsp;&nbsp;&nbsp; └ [*Log 10 Scatter Small*](Scatter.qmd#log-10-scatter-small)<br>&nbsp;&nbsp;&nbsp; └ [*Log 10 Scatter Big*](Scatter.qmd#log-10-scatter-big)<br>&nbsp;&nbsp;&nbsp; └ [*1.5 M bubble*](Scatter.qmd#sec-bubble)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Coloring Outside Bubble*](Scatter.qmd#coloring-outside-bubble)  | Creating Scatter Plots in R | Needs Finalizing |
| [***Chapter 5***](Volcano.qmd)<br>&nbsp; └ [*Chapter Overview*](Volcano.qmd#chapter-overview)<br>&nbsp; └ [*Packages*](Volcano.qmd#packages)<br>&nbsp; └ [*Labeling Your Data*](Volcano.qmd#labeling-your-data)<br>&nbsp; └ [*Creating a Volcano Plot*](Volcano.qmd#creating-a-volcano-plot)<br>&nbsp; └  [*Combined Graphs w/ Legends*](Volcano.qmd#combined-graphs-w-legends)<br>&nbsp; └ [*Combined Graphs w/ Unified Legend*](Volcano.qmd#combined-graphs-w-unified-legend)<br>&nbsp;&nbsp;&nbsp; └ [*Row Labels*](Volcano.qmd#row-labels)<br>&nbsp;&nbsp;&nbsp; └ [*Column Labels*](Volcano.qmd#column-labels)<br>&nbsp;&nbsp;&nbsp; └ [*Combining*](Volcano.qmd#combining)<br>&nbsp; └ [*Labeling*](Volcano.qmd#labeling)<br>&nbsp; └ [*Combined w/ Labels*](Volcano.qmd#combined-w-labels)<br>&nbsp; └ [*Logarithmic Scale*](Volcano.qmd#logarithmic-scale)  | Representing Significance of Data in R | Needs Finalizing |
| [***Chapter 6***](Line.qmd)<br>&nbsp; └ [*Libraries*](Line.qmd#libraries) | Creating Graphical Lines in R| Needs Finalizing |
| [***Chapter 7***](Sparkline.qmd)<br>&nbsp; | Creating Trend Lines in R | Needs Finalizing |
| [***Chapter 8***](Kernel.qmd)<br>&nbsp; └ [*Simple Kernel*](Kernel.qmd#simple-kernel)<br>&nbsp; └ [*Kernel Customizaiton*](Kernel.qmd#kernel-customization)<br>&nbsp;&nbsp;&nbsp; └ [*Log 10 Kernel*](Kernel.qmd#log-10-kernel)<br>&nbsp;&nbsp;&nbsp; └ [*Line Thickness*](Kernel.qmd#line-thickness)<br>&nbsp;&nbsp;&nbsp; └ [*Filtering*](Kernel.qmd#filtering)<br>&nbsp;&nbsp;&nbsp; └ [*Adjustment*](Kernel.qmd#adjustment)<br>&nbsp;&nbsp;&nbsp; └ [*Kernel Line Type*](Kernel.qmd#kernel-line-type)<br>&nbsp;&nbsp;&nbsp; └ [*Kernel Faceting*](Kernel.qmd#kernel-faceting) | Creating Lines Based on Density of Data | Needs Finalizing|
| [***Chapter 9***](Box and Whisker.qmd)<br>&nbsp; └[*Chapter Introduction*](Box and Whisker.qmd#chapter-introduction)<br>&nbsp;&nbsp;&nbsp; └ [*Installing R and Library Loading*](Box and Whisker.qmd#installing-r-and-library-loading)<br>&nbsp; └ [*Base R - Box and Whisker*](Box and Whisker.qmd#base-r---box-and-whisker)<br>&nbsp;&nbsp;&nbsp; └ [*Simple Boxplot*](Box and Whisker.wmd#simple-boxplot)<br>&nbsp;&nbsp;&nbsp; └ [*Customization in Base R*](Box and Whisker.qmd#customization-in-base-r)<br>&nbsp; └ [*`ggplot2`*](Box and Whisker.qmd#ggplot2)<br>&nbsp;&nbsp;&nbsp; └ [*Simple `ggplot2` Box Plot*](Box and Whisker.qmd#ggplot2-box-plot)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Data Creation*](Box and Whisker.qmd#data-creation)<br>&nbsp;&nbsp;&nbsp; └ [*Customizing `ggplot2`*](Box and Whisker.qmd#custom-ggplot2)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Basic Customization*](Box and Whisker.qmd#basic-customization)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Creating an Order*](Box and Whisker.qmd#creating-an-order)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*`geom_point`*](Box and Whisker.qmd#geompoint)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Outliers*](Box and Whisker.qmd#outliers)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Outlier Labeling*](Box and Whisker.qmd#outlier-labeling)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*`geom_jitter`*](Box and Whisker.qmd#geomjitter)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*`aes` Customization*](Box and Whisker.qmd#aes-custom)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Coloring Your Box Plot*](Box and Whisker.qmd#coloring-your-box-plot)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Multi Filtered*](Box and Whisker.qmd#multi-filtered)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*`geom_boxplot` Line Types*](Box and Whisker.qmd#geombox-line-types)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*`log10` Boxplots*](Box and Whisker.qmd#log10-boxplots)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Box Plot Parameters*](Box and Whisker.qmd#box-plot-parameters)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Boxplot Fences*](Box and Whisker.qmd#boxplot-fences)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Width of Box Plots*](Box and Whisker.qmd#width-of-box-plots)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Variable Widths*](Box and Whisker.qmd#variable-widths)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Creating a Median Line*](Box and Whisker.qmd#creating-a-median-line)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Coordinate Flip*](Box and Whisker.qmd#coordinate-flip)  | Creating Box and Whisker Plots in R | Complete |
| [***Chapter 10***](Violin.qmd)<br>&nbsp; └ [*Violin*](Violin.qmd-violin)<br>&nbsp; └ [*Violin Modification*](Violin.qmd#violin-modification)<br>&nbsp;&nbsp;&nbsp; └ [*Scale*](Violin.qmd#scale)<br>&nbsp;&nbsp;&nbsp; └ [*Trim*](Violin.qmd#trim)<br>&nbsp;&nbsp;&nbsp; └ [*Quantiles*](Violin.qmd#quantiles)<br>&nbsp;&nbsp;&nbsp; └ [*Error*](Violin.qmd#error)<br>&nbsp;&nbsp;&nbsp; └ [*Mean*](Violin.qmd#mean)<br>&nbsp;&nbsp;&nbsp; └ [*Violin and Boxplot*](Violin.qmd#violin-and-boxplot)<br>&nbsp;&nbsp;&nbsp; └ [*Violin and Sina*](Violin.qmd#violin-and-sina)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; └ [*Sina*](Violin.qmd#sina) | Creating Plots Violin Plots in R | Needs Finalizing |
| [***Chapter 11***](Pheatmap.qmd)<br>&nbsp; └ [*What is a heat map*](Pheatmap.qmd#what-is-a-heat-map)<br>&nbsp; └ [*Packages*](Pheatmap.qmd#packages)<br>&nbsp; └ [*Data View*](Pheatmap.qmd#data-view)<br>&nbsp; └ [*Pheatmap*](Pheatmap.qmd#pheatmap)<br>&nbsp;&nbsp;&nbsp; └ [*Clustering/Dendogram Control*](Pheatmap.qmd#clustering-dendogram-control)<br>&nbsp;&nbsp;&nbsp; └ [*Creating Gaps*](Pheatmap.qmd#creating-gaps)<br>&nbsp;&nbsp;&nbsp; └ [*Graph Color Annotation*](Pheatmap.qmd#graph-color-annotation)<br>&nbsp;&nbsp;&nbsp; └ [*Condition Annotation*](Pheatmap.qmd#condition-annotation)<br>&nbsp;&nbsp;&nbsp; └ [*Subset Annotation*](Pheatmap.qmd#subset-annotation) | Creating Heatmaps of Expression in R | Complete |
| [***Chapter 12***](Hydra.qmd)<br>&nbsp; └ [*Libraries*](Hydra.qmd#libraries)<br>&nbsp; └ [*Combinations*](Hydra.qmd#combinations)<br>&nbsp;&nbsp;&nbsp; └ [*Outlier*](Hydra.qmd#outlier) | Creating a combination of Plots in R | Needs Finalizing |